<a href="https://colab.research.google.com/github/lovishdany/AI-ML__NCU/blob/main/Practical%20-%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [ ]:
df= pd.read_csv('Book2.csv')

In [ ]:
df

        Name  Marks
0     Akshay     84
1     Akshat     63
2     Mahesh     77
3      Mamta     78
4    Sushant     90
5    Devansh     75
6     Garvit     49
7     Sachin     79
8    Gambhir     77
9     Gautam     52
10    Puneet     74
11  Siddarth     90

In [ ]:
data=df[['Marks']].values

In [ ]:
min= MinMaxScaler()
data=df[['Marks']].values
df_mm=min.fit_transform(data)
df_mm

array([[0.85365854],
       [0.34146341],
       [0.68292683],
       [0.70731707],
       [1.        ],
       [0.63414634],
       [0.        ],
       [0.73170732],
       [0.68292683],
       [0.07317073],
       [0.6097561 ],
       [1.        ]])

In [ ]:
scaler = StandardScaler()
df_ss=scaler.fit_transform(data)

In [ ]:
df_ss

array([[ 0.79430147],
       [-0.87373162],
       [ 0.23829044],
       [ 0.31772059],
       [ 1.27088235],
       [ 0.07943015],
       [-1.98575368],
       [ 0.39715074],
       [ 0.23829044],
       [-1.74746324],
       [ 0.        ],
       [ 1.27088235]])

In [ ]:
df2=df
df2['Marks']=df2['Marks']/100

In [ ]:
df2

        Name  Marks
0     Akshay   0.84
1     Akshat   0.63
2     Mahesh   0.77
3      Mamta   0.78
4    Sushant   0.90
5    Devansh   0.75
6     Garvit   0.49
7     Sachin   0.79
8    Gambhir   0.77
9     Gautam   0.52
10    Puneet   0.74
11  Siddarth   0.90